replicaCount: 1

image:
  repository: flashcatcloud/cprobe
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi



nodeSelector: {}

tolerations: []

affinity: {}

plugins:
  mysql: true
  redis: true
  kafka: false
  mongodb: false

mysql:
  config:
    global:
      scrape_interval: 15s
      external_labels:
        cplugin: 'mysql'

    scrape_configs:
      - job_name: 'mysql'
        static_configs:
          - targets:
              - '127.0.0.1:3306'
        scrape_rule_files:
          - 'rule_head.toml'
          - 'rule_coll.toml'


cprobe:
  config:
    global:
      extra_labels:
        region: bj
        zone: x
      metric_relabel_configs:
        - source_labels: [ __name__ ]
          regex: '(.*)'
          target_label: env
          replacement: 'production'
    writers:
      - url: http://127.0.0.1:9090/api/v1/write
        extra_labels:
          from: 9090
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: '(.*)'
            target_label: foo
            replacement: 'bar_${1}'
        concurrency: 10
        retry_times: 100
        retry_interval_millis: 3000
        basic_auth_user: ""
        basic_auth_pass: ""
        headers: []
        connect_timeout_millis: 500
        request_timeout_millis: 5000
        max_idle_conns_per_host: 2
        proxy_url: ""
        interface: ""
#        tls_skip_verify: false
#        tls_ca: /etc/ssl/certs/ca-certificates.crt
#        tls_cert: /etc/ssl/certs/client.crt
#        tls_key: /etc/ssl/certs/client.key
#        tls_key_pwd: password
#        tls_server_name: prometheus
        tls_min_version: "1.2"
        tls_max_version: "1.3"

      - url: http://127.0.0.1:9091/api/v1/write
        extra_labels:
          from: 9091

