apiVersion: apps/v1
kind: Deployment
metadata:
  name: cprobe-deployment
  namespace: cprobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cprobe
  template:
    metadata:
      labels:
        app: cprobe
    spec:
      containers:
        - name: cprobe-container
          image: flashcatcloud/cprobe:latest
          command: ["/app/cprobe"]
          ports:
            - containerPort: 5858
          volumeMounts:
            - name: cprobe-writer-config
              mountPath: /app/conf.d  # writer.yaml需要放在conf.d目录下
            - name: cprobe-mysql-config  # 当需要增加某个插件的配置目录的时候，就在这里添加volumeMount，创建一个子目录如conf.d/mysql
              mountPath: /app/conf.d/mysql
      volumes:
        - name: cprobe-writer-config
          configMap:
            name: cprobe-writer
        - name: cprobe-mysql-config  # 每个插件需要一个configmap，一个configmap中可以包含多个文件，如main.yaml，rule_coll.toml等
          configMap:
            name: cprobe-mysql

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cprobe-writer
  namespace: cprobe
data:
  writer.yaml: |
    global:
      extra_labels:
        colld: cprobe

    writers:
      - url: http://127.0.0.1:9090/api/v1/write
        concurrency: 1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cprobe-mysql
  namespace: cprobe
data:
  main.yaml: |
    global:
      scrape_interval: 15s
      external_labels:
        cplugin: 'mysql'