{{- if .Values.plugins.mysql}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cprobe.fullname" . }}-cprobe-writeconfigmap
  namespace: {{ .Release.Namespace }}
data:
  write.yaml: |
    {{- range $k, $v := .Values.cprobe.config }}
    {{ dict $k $v | toYaml | nindent 4 }}
    {{- end }}

{{- end}}